ONSdigital/dp-cli

- ansible/groups.go
- Migrated the ansible helper functions from the deprecated `dp` tool. 
- Refactored a bit.
> migrated ansible helper function from dp repo

- cmd/root_command.go
- main.go
Refactored `cmd.Load()` to include and `error` return type for future changes.
> added error to cmd.Load return vars

- project_generation/content/templates/ci/scripts/unit.tmpl
Fixed issue with incorrectly escaped parameter in unit test CI script template.
Generate a new project and the name should be in the unit.sh script
Anyone but me.
> Fix ci/unit.sh templating issue

- project_generation/content/templates/nomad.tmpl
###What
As per title, Web was not it is now.
Anyone except me
> Nomad task should match the vault policy

- project_generation/content/templates/config/config.tmpl
- project_generation/content/templates/mapper/mapper.tmpl
- project_generation/content/templates/mapper/mapper_test.tmpl
Renamed generated config value to make it more obvious it is an example
Ensure all uses of the config value have been effectively renamed.
Anyone but me
> Rename example config value for clarity

- README.md
- aws/ec2.go
- cmd/clean.go
- cmd/import_data.go
- cmd/remote_access.go
- cmd/root_command.go
- cmd/spew.go
- cmd/ssh.go
- config/config.go
- config/example_config.yml
- out/output.go
- ssh/ssh.go
Migrated remote access command from deprecated dp tool.
> migrated remote access command from deprecated dp tool

- README.md
- Added common issues section 
- fixed typo in example
> Add common issues and fix typo in example

- aws/ec2.go
Stop setting unneccessary rules on the web SG for production when the
website is already open to the world.  Additional rules will decrease
website performance and clutters the configuration.
> Stop cluttering prod web SG for no reason

- project_generation/README.md
Link to the generated projects repository in project generation README
> Add link to dp-hello-world to project gen README

- README.md
Added parts that were not covered, yet needed at this stage.
> doc. state what .yml bits to change & setup of go

- project_generation/COMPLETE_PROJECT_SETUP.md
Add working command line example and a bit of an explanation of it.
> doc. add complete command line example with explanation

- project_generation/content/templates/base-app/Makefile.tmpl
- project_generation/content/templates/base-app/ci/audit.yml.tmpl
- project_generation/content/templates/base-app/ci/scripts/audit.sh.tmpl
- project_generation/manifest.go
Add audit dependency to project generation
> Add audit dependency to project generation

- README.md
Accidentally committed to the wrong branch.  Cheery picked my change and created this new branch.
> Updated Go version from 1.13 to 1.15

- README.md
- project_generation/content/templates/event/README.md.tmpl
What
Update references to dp for main branch ahead of changing the default branch name.
How to review
typos and all occurrences found
Who can review
anyone
> Update dp links to use main branch

- aws/ec2.go
- go.mod
- go.sum
Updated to allow ssh to concourse on port 22.
> Updated concourse port

- .github/PULL_REQUEST_TEMPLATE.md
- project_generation/content/templates/library/Makefile.tmpl
- project_generation/content/templates/library/ci/lint.yml.tmpl
- project_generation/content/templates/library/ci/scripts/lint.sh.tmpl
See title
Check changes make sense
Anyone
> Add noop (placeholder) lint job to project generation repo

- README.md
> Update Go version to 1.16

- project_generation/content/templates/base-app/Makefile.tmpl
- project_generation/content/templates/base-app/ci/lint.yml.tmpl
- project_generation/content/templates/base-app/ci/scripts/lint.sh.tmpl
- project_generation/manifest.go
Add noop (placeholder) lint job to project generation
Add lint templates for base-app and include them in manifest
These were missed from #88
Check changes make sense
Anyone
> Add noop (placeholder) lint job to project generation

- project_generation/README.md
- project_generation/content/templates/base-app/README.md.tmpl
- project_generation/content/templates/controller/README.md.tmpl
- project_generation/content/templates/event/README.md.tmpl
- project_generation/content/templates/generic/README.md.tmpl
- project_generation/content/templates/library/README.md.tmpl
Use the preferred header style in readme templates
Also amended the project generation readme to tidy the possible values
Check the markdown generates the correct formatted text
Anyone
> Use headers in readme templates

- repository_creation/README.md
Add the missing `github` command
> Add command to readme

- command/scp.go
- command/ssh.go
- config/config.go
- config/example_config.yml
- scp/scp.go
- ssh/ssh.go
- added fix to allow ssm/ic for ci
- updated example_config.yml
> SSH/SCP for CI environment

- ssh/ssh.go
Fixed port forwarding when ssh'ing to awsb environments
Check if port forwarding works using one of the new environments e.g. sandbox
Anyone with access
> Fix Port Forwarding for AWSB Envs

- command/scp.go
- command/ssh.go
- scp/scp.go
updated scp.go to set env profile for awsb when doing a push
check uploading a file form a dir using the following command
-- dp scp sandbox web 1 <filename> .
-- login to the box and check if it has be uploaded in the home directory
anyone
> set env profile for scp push to awsb environment

- README.md
It was not clear to me what "ssh user" was being referred to in the README doc, so I added a note clarifying.
Read
Anyone
> Clarify ssh user

- go.mod
- go.sum
- project_generation/content/templates/api/service/initialise.go.tmpl
- project_generation/content/templates/controller/service/initialise.go.tmpl
- project_generation/content/templates/event/cmd/producer/main.go.tmpl
- project_generation/content/templates/event/event/consumer.go.tmpl
- project_generation/content/templates/event/event/consumer_test.go.tmpl
- project_generation/content/templates/event/features/steps/example_component.go.tmpl
- project_generation/content/templates/event/features/steps/steps.go.tmpl
- project_generation/content/templates/event/service/initialise.go.tmpl
- project_generation/content/templates/event/service/interfaces.go.tmpl
- project_generation/content/templates/event/service/mock/initialiser.go.tmpl
- project_generation/content/templates/event/service/service.go.tmpl
- project_generation/content/templates/event/service/service_test.go.tmpl
Update template dependencies . The changes include:
- Update to version 3 of kafka library
- Update to version 2 of the dp net library
The repos for api, base-app, controller, event, generic and library has been generated and tested. 
Anyone but me
> Update dependencies for the template

- config/example_config.yml
Fixes some minor issues with the example config for AWS-B environments
Ensure your config matches the example one and test that dp-cli works for both dp-prod and dp-ci.
Anyone with experience of AWS-B.
> Fix AWS-B errors in example config

- dp-hello-world-controller/assets/locales/service.cy.toml
- dp-hello-world-controller/assets/locales/service.en.toml
- dp-hello-world-controller/assets/templates/hello-world.tmpl
- project_generation/content/templates/controller/Makefile.tmpl
- project_generation/content/templates/controller/assets/assets.go.tmpl
- project_generation/content/templates/controller/assets/locales/service.cy.toml.tmpl
- project_generation/content/templates/controller/assets/locales/service.en.toml.tmpl
- project_generation/content/templates/controller/assets/templates/hello-world.tmpl.tmpl
- project_generation/content/templates/controller/ci/scripts/component.sh.tmpl
- project_generation/content/templates/controller/config/config.go.tmpl
- project_generation/content/templates/controller/config/config_test.go.tmpl
- project_generation/content/templates/controller/features/hello_world.feature.tmpl
- project_generation/content/templates/controller/features/helloworld.feature.tmpl
- project_generation/content/templates/controller/features/steps/example_component.go.tmpl
- project_generation/content/templates/controller/features/steps/steps.go.tmpl
- project_generation/content/templates/controller/handlers/clients.go.tmpl
- project_generation/content/templates/controller/handlers/handlers.go.tmpl
- project_generation/content/templates/controller/main.go.tmpl
- project_generation/content/templates/controller/main_test.go.tmpl
- project_generation/content/templates/controller/mapper/mapper.go.tmpl
- project_generation/content/templates/controller/mapper/mapper_test.go.tmpl
- project_generation/content/templates/controller/routes/routes.go.tmpl
- project_generation/content/templates/controller/service/service.go.tmpl
- project_generation/content/templates/controller/service/service_test.go.tmpl
- project_generation/manifest.go
- project_generation/project_generation.go
Add component tests to controller project type. Tests support UI feature.
Review code changes. Check/review and run tests in newly generated example controller project.
Anyone
> Add component tests to controller project type

- README.md
Updated README to include instructions around brew installation
Proof read steps, check nothing is missing and all makes sense
Anyone
> Brew Installation Instructions

- .gitignore
- README.md
- aws/ec2.go
- command/ssh.go
- config/example_config.yml
- go.mod
- go.sum
- out/output.go
- scp/scp.go
updated read me 
updated env.Name to prod
Check for typos 
Check if it read correct
Anyone
> updated readme and env.Name to prod

- README.md
Updated bad command in README docs.
Run new command and see if it works. 
Any dev.
> Correct URL typo in README

- repository_creation/MAIN_TO_MASTER_GUIDE.md
update instructions to match Github wording
Eyeball
Anyone
> update instructions to match Github wording

- README.md
Update to Go 1.19 as it is the latest version at the moment.
Also revert to mention that it won't work with any version lower than 1.11 due to Go Modules
Check changes make sense
Anyone
> Refer to latest Go 1.19

- project_generation/content/templates/base-app/nomad.tmpl
Updated project generator template to use eu-west-2 for newly generated apps
Ensure only change is to AWS region in nomad template file.
Anyone but me
> Switch AWS region in project gen template

- project_generation/content/templates/api/.golangci.yml.tmpl
- project_generation/content/templates/base-app/.golangci.yml.tmpl
- project_generation/content/templates/base-app/README.md.tmpl
- project_generation/content/templates/base-app/ci/build.yml.tmpl
- project_generation/content/templates/base-app/ci/component.yml.tmpl
- project_generation/content/templates/base-app/ci/unit.yml.tmpl
- project_generation/content/templates/controller/.golangci.yml.tmpl
- project_generation/content/templates/controller/Makefile.tmpl
- project_generation/content/templates/event/.golangci.yml.tmpl
- project_generation/content/templates/event/Makefile.tmpl
- project_generation/content/templates/library/.golangci.yml.tmpl
- project_generation/content/templates/library/Makefile.tmpl
- project_generation/helpers.go
- project_generation/project_generation.go
I recently had to create a new project and some of the files it generated were incorrect or out of date. I have fixed some of those issues, the more significant one being that I've added the Debian version to the Go images in the pipeline.
Generate a new project and check that the files created with the templates modified as part of this PR contain the new changes.
Anyone.
> Add the Debian Codename to the Go image (plus other small fixes)

- project_generation/content/templates/api/main.go.tmpl
- project_generation/content/templates/api/service/service.go.tmpl
- project_generation/content/templates/base-app/config/config.go.tmpl
- project_generation/content/templates/base-app/config/config_test.go.tmpl
- project_generation/content/templates/controller/Makefile.tmpl
- project_generation/content/templates/controller/config/config.go.tmpl
- project_generation/content/templates/controller/main.go.tmpl
- project_generation/content/templates/controller/service/service.go.tmpl
- project_generation/content/templates/event/cmd/producer/main.go.tmpl
- project_generation/content/templates/event/config/config.go.tmpl
- project_generation/content/templates/event/event/consumer.go.tmpl
- project_generation/content/templates/event/event/consumer_test.go.tmpl
- project_generation/content/templates/event/features/steps/example_component.go.tmpl
- project_generation/content/templates/event/features/steps/steps.go.tmpl
- project_generation/content/templates/event/service/initialise.go.tmpl
- project_generation/content/templates/event/service/interfaces.go.tmpl
- project_generation/content/templates/event/service/mock/initialiser.go.tmpl
- project_generation/content/templates/event/service/service.go.tmpl
- project_generation/content/templates/event/service/service_test.go.tmpl
Added open telemetry to the template generation functionality
Check the templates generate as expected
Fran Moore, Chales Colbourn, Gordon Kerr
@HuwONS @gordonkerrONS @franmoore05 @hhsons @charlescolbourn
> Add open telemetry instrumentation to template files

- README.md
Minor improvements to the readme following my recent reinstall.
Added the brew install option for the session manager plugin as well as adding the missing optional nisra infrastructure repo to list of optional repos to clone.
!me
> Improve readme to make set up clearer

- project_generation/content/templates/base-app/Dockerfile.concourse.tmpl
As per title
Visual inspection and ensure same change as whats here:
https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/244/files
Anyone
> update Dockerfile.concourse to use ubuntu22.04 image
