ONSdigital/dp-cli

main.go

- Refactored main to use new run pattern.
- deleted the `dp-cli` go binary from the repo - binary shouldn't be commited.

refactor main to use run pattern and delete go binary from repo

---

Makefile
cmd/root_command.go
project_generation/content/templates/Dockerfile.concourse.tmpl
project_generation/content/templates/ci/build.tmpl
project_generation/content/templates/ci/scripts/build.tmpl
project_generation/content/templates/ci/scripts/unit.tmpl
project_generation/content/templates/ci/unit.tmpl
project_generation/content/templates/nomad.tmpl
project_generation/helpers.go
project_generation/manifest.go
project_generation/project_generation.go
repository_creation/edit_repository.go

Fixes various bus in project generation, including…
- Capitalise generated markdown filenames
- Fix quotation of WEB_TASK_COUNT in nomad template
- Make generated scripts executable
- Get version from git commit on build
- Bring CI script templates up to go 1.13 compatibility
- Make script able to be run from any directory by making templates path absolute
- Embed version number from git history (based on release tags / commits)

Project generation bug fixes

---

project_generation/content/templates/handlers/handlers.tmpl
project_generation/content/templates/main.tmpl
project_generation/content/templates/mapper/mapper.tmpl
project_generation/content/templates/mapper/mapper_test.tmpl
project_generation/content/templates/routes/routes.tmpl
project_generation/helpers.go

The namespaces in generated projects were not fully qualified with github.com/ONSdigital
The initialises of git modules has been updated as well as all templates that were using the shorthand package names.

Use fully qualified namespaces for git module

---

project_generation/content/templates/ci/unit.tmpl

Remove incorrect indentation in template for ci/unit.yml.
This caused the generated project to fail to run unit tests on CI.
Ensure correct yaml indentation for affected line.
Anyone but me

Fix indentaition in template for ci/unit.yml

---

README.md
aws/ec2.go

The network ACL rules have been changed so that only the security group
needs to be updated to grant access.  This will allow us to avoid the 40
rule ACL limit.
🚨 Depends on:
* https://github.com/ONSdigital/dp-setup/pull/773
* https://github.com/ONSdigital/dp-setup/pull/774

Fix ACL rule limit reached

---

cmd/ssh.go

Fixed defect in instance subcommand where only ever connecting to last listed instance.
`env` and `instance` variable values changing with each iteration of loop. Created new local vars to prevent this happening.

fixed defect caused by variable scope

---

.gitignore
Makefile
README.md
cmd/dp/main.go
command/clean.go
command/create_repo.go
command/generate.go
command/import_data.go
command/remote_access.go
command/root_command.go
command/spew.go
command/ssh.go
command/version.go
customisemydata/neo4j.go
out/output.go
project_generation/COMPLETE_PROJECT_SETUP.md
project_generation/README.md
project_generation/helpers.go
project_generation/manifest.go
project_generation/project_generation.go
repository_creation/README.md
repository_creation/create_repository.go

I have renamed the `dp-cli` command to `dp`. However the repository has remained as `dp-cli` so I have instead moved the main.go into `cmd/dp`. Unfortunately there was already an existing directory called `cmd` so I have renamed this `command`. Longer term we should probably restructure the repo but this is minimal for now that preserves the convention of a main command being in a package of th same name (ie. `dp` is in a directory called `dp`).
Anyone can review.

Rename the built command from `dp-cli` to `dp`

---

.gitignore

The documentation says to create a `dp-cli-config.yml` file, but that file is not currently ignored. Rather than having to stash the change constantly, or risk committing a personal file, let's get git to ignore it for us!

Add dp-cli-config.yml filename to gitignore

---

Makefile
command/ssh.go
go.mod
ssh/ssh.go
ssh/ssh_test.go

Added port forwarding/tunnelling to the `dp ssh` command. I used the docker style of forwarding rules hence the `-p 123:456` style, although I think `--port` is clearer than Docker's `--publish` for the long form.
Anyone can review, but particularly those who use port forwarding a lot.

Add port forwarding (tunnelling) to dp ssh

---

README.md

Update the link to the AWS credentials documentation as it has been moved from dp-setup to dp.
🚨 Depends on: https://github.com/ONSdigital/dp/pull/106

Update the link to the AWS credentials documentation

---

project_generation/content/templates/base-app/nomad.tmpl

In publishing the code generation would create task with the service name not in quotes. This would cause an unknown token error. This adds the quotes in.
Anyone except me

Fix nomad plan for code generation

---

project_generation/content/templates/base-app/README.md.tmpl
project_generation/content/templates/base-app/config/config.go.tmpl
project_generation/content/templates/base-app/config/config_test.go.tmpl
project_generation/content/templates/controller/README.md.tmpl
project_generation/content/templates/controller/config/config.go.tmpl

Update repo generation tool templates with the new default configuration for healthcheck
Defaults should be 30 seconds for health check interval and 90 seconds for health check critical timeout

Update repo generation tool templates

---

README.md
aws/ec2.go
command/remote_access.go
command/ssh.go
ssh/ssh.go

- `remote allow` now does `deny` first (new `--no-deny` flag retains old behaviour/IPs)
- tidy up some `out` strings (mostly superfluous newlines)

`remote allow` does `deny` first (new `--no-deny` flag retains old behaviour/IPs)

---

command/root_command.go

If the user does not have access to dp-setup the cli would previously
fail, blocking use of any of the other features of the tool. By changing
this error to warning we enable a wider range of users who may not have
the dp-setup repo cloned to still use the other subcommands.

Enable running of dp without SSH setup

---

README.md
command/import_data.go
command/root_command.go
command/ssh.go
config/config.go
config/example_config.yml
customisemydata/neo4j.go

Allow the user to customise where the dp-hierarchy-api and
dp-code-list-scripts repos are checked out. This is mostly to support
the fact that these repos will need to move outside the GOPATH in order
to work for modules. Prior to this change these repos would have to be
checked out twice.
One drawback to this change is that everyone will need to add the two new configs, however I was hesitant to add the existing paths under the GOPATH as a default as this would perpetuate the double clone situation. A clean break feels like the way to go in this case.

Allow repo paths to be customised

---

customisemydata/neo4j.go

By building the full path to the script locations in the other repos we
simplify the config file by allowing us to just point to the root of the
repo.

Build full path to scripts to simplify configs

---

aws/ec2.go
command/remote_access.go
config/config.go

sample config, to restore old behaviour:
```
environments:
- name: cmd-dev
extra-ports:
publishing:
- 80
```

remove access to port 80 for Publishing SG, allow config to add back in

---

repository_creation/create_repository.go

GitHub now generates repositories in a manner that the main working branch is now called 'main' instead of 'master'. This fixes the repo generation tool to fall in line with this change. References to 'master' are now set to 'main'
`$make install`
`$dp `
`$dp-create-repo github`
Check that there are no errors and then go to GitHub can check that the correct branch protections have been applied to both the main and develop branch.
Anyone except me

Repo generation tool now works with main as the default 'master' branch

---

project_generation/COMPLETE_PROJECT_SETUP.md
repository_creation/MAIN_TO_MASTER_GUIDE.md
repository_creation/README.md

Documentation update around the move to `main` from `master`. For the time being manual actions are required after generating a project, these are now documented. Note that these actions are only temporary until work to resolve CI branch changes have been completed.
Two README.md have been edited with interim warnings and actions
Anyone except me

Update documentation around interim actions for the repo gen tool

---

project_generation/content/templates/api/api/api.go.tmpl
project_generation/content/templates/api/api/hello.go.tmpl
project_generation/content/templates/api/service/service_test.go.tmpl
project_generation/content/templates/base-app/config/config.go.tmpl
project_generation/content/templates/base-app/config/config_test.go.tmpl
project_generation/project_generation.go

Fix errors seen when running ```dp generate-project```, to generate an API where `make test` pass and `make debug` runs
- Create a path for the mock file
- Use an unused import
- Update the service_test and config_test to use a port variable
- Update the config file to have localhost

Resolve path, unused import and test errors when creating an API

---

ansible/groups.go

During the upgrade to ansible 2.10 the groups in the `hosts` file were
changed. Long term it might be best to change the way we are getting the
groups or even included them within this repo, but in the meantime the
parsing has been updated to work with the latest ansible inventory.

Fix ansible groups parsing after ansible upgrade

---

project_generation/content/templates/api/swagger.yaml.tmpl

Extend the API swagger spec template to include health endpoint.
This will allow developers to inherit the correct spec for health endpoint when generating a new repo that contains an API service.
Use the [Swagger Editor](https://editor.swagger.io/) to view API generation template for swagger spec
Make sure the spec abides by [dp healthcheck standards doc](https://github.com/ONSdigital/dp/blob/main/standards/HEALTH_CHECK_SPECIFICATION.md)
Anyone

Add health endpoint into swagger spec template for API generation tool

---

README.md
aws/ec2.go
command/ssh.go
ssh/ssh.go

I found looking up an IP (from an alert, say) to find out which host it was was slowing me down in getting on to the box and fixing :all_the_things:
so this PR let's us just use:
- `dp ssh $env $ip` to get there quickly
- `dp ssh $env` also informs you which host(s) IPs refer to, if you prefer just to look it up

add ability to ssh by IP: `dp ssh $env 10.1.2.3`

---

project_generation/content/templates/controller/Makefile.tmpl
project_generation/manifest.go

The version variables have been moved to the service package and the Makefile needs to be updated to refer to the new location
This was missed from https://github.com/ONSdigital/dp-cli/pull/97
1. `make build`
2. Create a hello world controller:
`./dp generate-project --create-repository n --name "dp-hello-world-controller" --description "Example controller project generated by dp-cli" --go-version 1.17.1 --port 8124 --project-location . --type controller`
3. Check the generated `Makefile` is identical to the one in [dp-hello-world-controller](https://github.com/ONSdigital/dp-hello-world/blob/master/dp-hello-world-controller/Makefile)
4. Check there are no errors when running `make build` on the recently generated controller and that it starts with `make debug`
Anyone

Fix Makefile for controllers

---

config/config.go

revert change to URL for getting IP address, needs to return IPv4
`dp remote allow develop` should now work
Describe who worked on the changes, so that other people can review.

revert URL for getting IP to avoid IPv6

---

README.md
project_generation/content/templates/library/ci/build.yml.tmpl
project_generation/content/templates/library/ci/lint.yml.tmpl
project_generation/content/templates/library/ci/scripts/audit.sh.tmpl
project_generation/content/templates/library/ci/unit.yml.tmpl

Libraries should be tied to latest because the dependency is defined by the app using the library instead. This ensures the library is kept up to date for an app.
Update README to refer to GO 1.18
Sense check
Anyone

Use latest go docker image for libraries

---

project_generation/content/templates/api/main_test.go.tmpl
project_generation/content/templates/controller/main_test.go.tmpl
project_generation/content/templates/event/main_test.go.tmpl

Set Godog to strict mode, to avoid the issues described in https://github.com/ONSdigital/dp-legacy-cache-api/pull/21.
Currently, when a Godog step is missing, a warning is issued, and a step (and scenario) is marked as undefined when running the component tests. However, the exit code is still 0, which means that the pipeline will not fail when a step is undefined. This means that a malformed step could inadvertently make a whole scenario to go untested, and the Component Test pipeline job would still pass.
As part of this change, we're changing this behaviour, so that the exit code is not 0 when a step is pending or undefined.
Ensure that the templates are not broken.
Anyone.

Fail test suite when there are pending or undefined steps
